---
- name: set user, key, hostname, hosts
  hosts: cse
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - common

- name: deploy hadoop | hadoop
  hosts: cse
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: cse
  roles:
    - hadoop
